system-test: refactor custom host certificate support
This patch refactors and hopefully simplifies the host credential
support within system-test.

Although the patch modifies the hostCredential and, to a minor
extent, the populate script, the default system-test build is not
changed.  A host credential is stored in git that support 'localhost'
connections.  This is used by default.  Therefore the system-test
continues to work without storing any files externally.

As currently, the hostCredential utility can create host credentials,
either 'localhost'-only or with SubjectAlternativeName that match all
discovered possible FQDNs for the host.  The 'localhost'-only
certificate allows easy renewing of the git-stored credential.  The
SAN certificate is to allow some clients that use the Globus GSI
library to work correctly (gSOAP-based ones, but potentially others,
too).

The difference is that, in addition to storing the certificate in the
target/dcache directory, it is also stored in ~/.globus directory.
The populate script has been updated so that, if it detects a stored
host credential in ~/.globus, this is used in preference to the
git-stored credential.

Previously hostCredential required the --install option in addition
to the --generate option to trust the generated certificate.  Now,
this is implied: the script ensures that the generated certificate is
trusted.

The --clean command is added.  This removes all files in ~/.globus
directory that the command installs.  After running this command, the
system-test build will use the git-stored host credential.

The --install command installs all unknown certificates and
signing-policy files in ~/.globus/certificates.  This is similar to
what is does currently, but now it does this so that that installed
files may be deleted later on (by --clean)

The populate script continues to check if dCache-trusted certificates
are trusted by the user.  The output if one or more files are missing
has changed: rather than listing the missing files with instructions,
the developer is told to use 'hostCredential --trust' to fix the
problem.

If a dCache-trusted certificate is trusted by the developer, the
populate script checks that they are byte-wise identical files.  This
test is useful if the Disposable CA changes (e.g.,
'localhost'-certificate is renewed) as the filenames will remain the
same but have different contents.

Target: trunk
Requires-note: no
Requires-book: no
Patch: http://rb.dcache.org/r/5705
Acked-by: Gerd Behrmann

diff --git a/packages/system-test/src/main/skel/bin/hostCredentials b/packages/system-test/src/main/skel/bin/hostCredentials
--- a/packages/system-test/src/main/skel/bin/hostCredentials
+++ b/packages/system-test/src/main/skel/bin/hostCredentials
@@ -5,7 +5,12 @@ set -e
 rel_path=$(dirname $0)/../etc/grid-security
 mkdir -p $rel_path/certificates
 TARGET_DIR=$(cd $rel_path;pwd)
-TARGET_CERTIFICATES=$TARGET_DIR/certificates
+TARGET_TRUST_STORE=$TARGET_DIR/certificates
+
+OUR_TRUST_STORE=$HOME/.globus/dcache-systemtest-certificates
+USER_TRUST_STORE=$HOME/.globus/certificates
+SYSTEM_TRUST_STORE=/etc/grid-security/certificates
+HOST_CRED_STORE=$HOME/.globus
 
 while [ $# -gt 0 ]; do
     case "$1" in
@@ -19,66 +24,87 @@ while [ $# -gt 0 ]; do
 	    shift
 	    ;;
 
+	--clean)
+	    clean=1
+	    shift
+	    ;;
+
 	--generate)
 	    generate=1
 	    shift
 	    ;;
 
 	--help|-h)
-	    echo "Usage: $0 [--generate] [--only-localhost] [--install]"
+	    echo "Usage:"
+	    echo "    $0 --generate [--only-localhost]"
+	    echo "    $0 --install"
+	    echo "    $0 --clean"
 	    echo
-	    echo "Tool for handling and generating grid host credentials suitable"
-	    echo "for testing dCache"
+	    echo "Tool for managing grid host credentials suitable for testing dCache"
 	    echo
-	    echo "Options:"
-	    echo "     --generate        create a CA and host credentials"
-	    echo "     --only-localhost  only include 'localhost' as subjAltName"
-	    echo "     --install         install CA files in ~/.globus/certificates"
+	    echo "Commands:"
+	    echo "     --generate        create new CA and host credentials"
+	    echo "     --install         install (\"trust\") any missing certificate material"
+	    echo "     --clean           remove managed files from the ~/.globus directory"
 	    echo "  -h --help            provide this information"
 	    echo
-	    echo "If --generate is specified then this command will generate host"
-	    echo "credentials (private key and certificate) using a disposable CA,"
-	    echo "which is also generated.  The results will be the files "
-	    echo "'hostkey.pem' and 'hostcert.pem' and four files written in the"
-	    echo "'certificates' directory that start with a 8-digit hexadecimal"
-	    echo "number.  All these locations are relative to the target directory:"
+	    echo "Options:"
+	    echo "     --only-localhost  only include 'localhost' as subjAltName"
 	    echo
-	    echo "    $TARGET_DIR"
+	    echo "This tool has three modes of operation: generating new credentials,"
+	    echo "trusting dCache credentials and removing files.  These correspond to"
+	    echo "the --generate, --install and --clean commands respectively"
+	    echo
+	    echo "GENERATE:"
+	    echo
+	    echo "The --generate command will create CA credentials (a private key and"
+	    echo "self-signed certificate) and, using this CA, generate host credentials"
+	    echo "(another private key and certificate).  Once the CA key has been used to"
+	    echo "sign the host certificate, it is destroyed.  Therefore, this CA cannot sign"
+	    echo "any further certificates."
+	    echo
+	    echo "The generated CA certificate and host credentials are stored in the"
+	    echo "current system-test deployment and also in the users ~/.globus directory."
+	    echo "The user's trust store is also updated so that users will trust the new CA."
+	    echo
+	    echo "SubjectAlternativeName"
+	    echo
+	    echo "In general, a certificate may include zero or more Subject Alternative"
+	    echo "Names.  For a host certificate, such Subject Alternative Names can"
+	    echo "include all the DNS names through which this machine may be contacted."
+	    echo
+	    echo "By default, this script generates a host certificate with Subject"
+	    echo "Alternative Name of 'localhost', the output of running 'uname -n'"
+	    echo "and the FQDNs from 'hostname -A'.  This host certificate will always"
+	    echo "work, but is specific to the host it was generated on, and (in general)"
+	    echo "cannot be shared between hosts."
+	    echo
+	    echo "The '--only-localhost' option limits the Subject Alternative Names"
+	    echo "to just 'localhost'.  The resulting certificate should work when client"
+	    echo "connects to 'localhost'.  It is generic, so may be stored in a VCS."
+	    echo "However, on some platforms, clients that use Globus native libraries"
+	    echo "seem unable to use this certificate."
 	    echo
 	    echo "TRUST"
 	    echo
-	    echo "The Certificate Authority is generated afresh each time this"
-	    echo "command is run with --generate and the CA's private key is thrown"
-	    echo "away after signing the host certificate.  Therefore it is safe to"
-	    echo "trust the CA as no further certificates can be generated."
+	    echo "When testing dCache, a client must trust that the information presented"
+	    echo "by the server is correct (e.g., that the server really is 'localhost')."
+	    echo "This is done by the client trusting the CA that signed the certificate,"
+	    echo "which is done by including the CA's certificate in a trust store."
 	    echo
-	    echo "Trusting the CA may involve copying the CA certificate and"
-	    echo "signing_policy files into a trust store.  Users typically have"
-	    echo "two: the user-local trust store (~/.globus/certificates) and"
-	    echo "the system-wide trust store (/etc/grid-security/certificates)."
-	    echo "Copying the files into either one is sufficient."
+	    echo "The --install command will update the user's trust store (the directory"
+	    echo "~/.globus/certificates) so that the CA that signed the dCache certificate"
+	    echo "is trusted."
 	    echo
-	    echo "As a convenience, when the --install option is specified the"
-	    echo "generated CA files (certificate and signing_policy files) are"
-	    echo "copied into the ~/.globus/certificates directory.  If --install"
-	    echo "is specified without --generate then the contents of the target"
-	    echo "directory is copied."
-	    echo 
-	    echo "SUBJECT ALTERNATIVE NAME:"
+	    echo "NB. The --install command is not needed when using the --generate command as"
+	    echo "    this command will update the user's trust store automatically."
 	    echo
-	    echo "A certificate may include zero or more Subject Alternative Names."
-	    echo "For a host certificate, such Subject Alternative Names normally"
-	    echo "includes all the DNS names through which this machine may be "
-	    echo "contacted.  By default, when generating a host certificate,"
-	    echo "'localhost', the output of running 'uname -n' and all known FQDNs"
-	    echo "found by running 'hostname -A' are added as Subject Alternative Names."
-	    echo "The resulting host certificate should always work, but is specific"
-	    echo "to this host."
+	    echo "CLEAN"
 	    echo
-	    echo "The '--only-localhost' option limits the Subject Alternative Names"
-	    echo "to just 'localhost'.  The resulting certificate may not work in all"
-	    echo "circumstances, but is generic and so may be placed in some central"
-	    echo "location (e.g., a VCS) for general use."
+	    echo "The --clean command removes all the files that this script stored in the"
+	    echo "~/.globus directory.  In effect, this is the reverse of running either"
+	    echo "the --generate or --install commands, although reinstalling system-test is"
+	    echo "needed to completely undo --generate."
 	    exit 0
 	    ;;
 
@@ -95,10 +121,28 @@ if [ "$only_localhost" = "1" ] && [ ! "$generate" = "1" ]; then
     exit 1
 fi
 
-if [ ! "$generate" = "1" ] && [ ! "$install" = "1" ]; then
-    echo "Either --generate, --install or both must be specified.  Try --help for"
+if [ ! "$clean$install$generate" = "1" ]; then
+    echo "Exactly one of --clean, --install and --generate must be specified.  Try --help for"
     echo "details."
     exit 1
+fi
+
+function clean_dot_globus
+{
+    rm -f $HOST_CRED_STORE/dcache-systemtest-host*.pem
+
+    if [ -d $OUR_TRUST_STORE ]; then
+	for file in $OUR_TRUST_STORE/*; do
+	    rm -f $USER_TRUST_STORE/$(basename $file)
+	done
+    fi
+
+    rm -rf $OUR_TRUST_STORE
+}
+
+if [ "$clean" = "1" ]; then
+    clean_dot_globus
+    exit 0
 fi
 
 function list_potential_subjaltname()
@@ -114,7 +158,6 @@ function cleanup_ca_dir()
 {
     rm -rf $CA_DIR
 }
-
 
 if [ "$generate" = "1" ]; then
     CA_DIR=$(mktemp -d)
@@ -217,31 +260,38 @@ EOF
     hash_old=$(openssl x509 -in $CA_CERT -noout -subject_hash_old)
     hash_new=$(openssl x509 -in $CA_CERT -noout -subject_hash)
 
-    cp $CA_CERT $TARGET_CERTIFICATES/$hash_old.0
-    cp $CA_CERT $TARGET_CERTIFICATES/$hash_new.0
+    cp $CA_CERT $TARGET_TRUST_STORE/$hash_old.0
+    cp $CA_CERT $TARGET_TRUST_STORE/$hash_new.0
 
-    cat > $TARGET_CERTIFICATES/$hash_old.signing_policy <<EOF
+    cat > $TARGET_TRUST_STORE/$hash_old.signing_policy <<EOF
 access_id_CA    X509    '/DC=org/DC=dCache/CN=disposable-CA'
 pos_rights      globus  CA:sign
 cond_subjects   globus  '"/DC=org/DC=dCache/*"'
 EOF
-    cp $TARGET_CERTIFICATES/$hash_old.signing_policy $TARGET_CERTIFICATES/$hash_new.signing_policy
+    cp $TARGET_TRUST_STORE/$hash_old.signing_policy $TARGET_TRUST_STORE/$hash_new.signing_policy
 
     mv $CA_DIR/hostcert.pem $TARGET_DIR/hostcert.pem
     openssl rsa -in $CA_DIR/hostkey.pem -out $TARGET_DIR/hostkey.pem >/dev/null 2>&1
+
+    clean_dot_globus
+
+    mkdir -p $HOST_CRED_STORE
+
+    cp $TARGET_DIR/hostcert.pem $HOST_CRED_STORE/dcache-systemtest-hostcert.pem
+    cp $TARGET_DIR/hostkey.pem $HOST_CRED_STORE/dcache-systemtest-hostkey.pem
 fi
 
 
-if [ "$install" = "1" ]; then
-    TRUST_STORE=$HOME/.globus/certificates
-    mkdir -p $TRUST_STORE
-    if [ "$generate" = "1" ]; then
-	cp $TARGET_CERTIFICATES/$hash_old.0 \
-	    $TARGET_CERTIFICATES/$hash_new.0 \
-	    $TARGET_CERTIFICATES/$hash_old.signing_policy \
-	    $TARGET_CERTIFICATES/$hash_new.signing_policy \
-	    $TRUST_STORE
-    else
-	cp $TARGET_CERTIFICATES/* $TRUST_STORE
+# Add any missing trust in user's trust-store
+
+mkdir -p $OUR_TRUST_STORE
+
+for file in $TARGET_TRUST_STORE/*; do
+    name=$(basename $file)
+
+    if ! cmp -s $file $SYSTEM_TRUST_STORE/$name &&
+       ! cmp -s $file $USER_TRUST_STORE/$name; then
+	cp $file $OUR_TRUST_STORE/$name
+	ln -s $OUR_TRUST_STORE/$name $USER_TRUST_STORE/$name
     fi
-fi
+done
diff --git a/packages/system-test/src/main/skel/bin/populate b/packages/system-test/src/main/skel/bin/populate
--- a/packages/system-test/src/main/skel/bin/populate
+++ b/packages/system-test/src/main/skel/bin/populate
@@ -80,37 +80,51 @@ $username
 EOF
 fi
 
-scan_missing_ca_files() {
-    for path in "$@"; do
-        file=$(basename $path)
+if [ -f ~/.globus/dcache-systemtest-hostcert.pem ]; then
+    cp ~/.globus/dcache-systemtest-hostcert.pem etc/grid-security/hostcert.pem
+    cp ~/.globus/dcache-systemtest-hostkey.pem etc/grid-security/hostkey.pem
+    ## WORK-AROUND: we're using assemble maven plugin.  This doesn't allow files to be overwritten.
+    ##              As the VCS-supplied CA certificates are copied before the system- and user- trust
+    ##              stores and the generated host certificate's CA certificates and VCS-supplied
+    ##              CA certificate have the same hash (=> same filename), dCache's trust-store will
+    ##              have the VCS-supplied CA certificate.  This means that dCache won't trust the CA
+    ##              of its host certificate.  To fix this, we copy the CA certificates manually.
+    cp ~/.globus/dcache-systemtest-certificates/* etc/grid-security/certificates
+else
+    echo
+    echo "INFO: using VCS-supplied credentials.  These should work, but Globus native clients on some"
+    echo "      platforms will fail.  Use 'hostCredentials --generate' command to generate a host-"
+    echo "      specific credential if you have this problem."
+fi
 
-        if [ ! -f ~/.globus/certificates/$file -a ! -f /etc/grid-security/certificates/$file ]; then
-            echo $path
-        fi
-    done
+
+function compare()
+{
+    rc=0
+    cmp -s "$1" "$2" || rc=$?
+    if [ $rc == 1 ]; then
+	echo
+	echo "WARNING: files $1 and $2 are different."
+	echo "         This difference can cause authentication problems, so should be resolved."
+    fi
 }
 
-missing=$(scan_missing_ca_files etc/grid-security/certificates/*)
+warn_missing_trust=0
+for path in etc/grid-security/certificates/*; do
+    file=$(basename $path)
 
-if [ ! -z "$missing" ]; then
-    echo
-    echo "**"
-    echo "**  WARNING"
-    echo "**"
-    echo "**  The following files are missing from your grid-security"
-    echo "**  trust-store.  This will likely result in secure clients"
-    echo "**  being unable to use system-test dCache instance as they"
-    echo "**  will not trust the certificate dCache presents."
-    echo "**"
-    echo "**  To fix this, copy these files into either the"
-    echo "**  /etc/grid-security/certificates or ~/.globus/certificates"
-    echo "**  directory.  Copying into one directory is enough; either"
-    echo "**  directory will work; if uncertain copy to"
-    echo "**  ~/.globus/certificates."
-    echo "**"
-    for file in $missing; do
-        echo "**    $file"
-        echo "**"
-    done
-    echo
-fi
+    if [ ! -f ~/.globus/certificates/$file -a ! -f /etc/grid-security/certificates/$file ]; then
+	if [ $warn_missing_trust = 0 ]; then
+	    echo
+	    echo "WARNING: not all certificates dCache trusts are trusted by YOU.  This can cause authentication"
+	    echo "         problems when trying to use dCache.  To solve this problem use the 'hostCredentials --install'"
+	    echo "         command."
+	    warn_missing_trust=1
+	fi
+	continue
+    fi
+
+    compare $path ~/.globus/certificates/$file
+    compare $path /etc/grid-security/certificates/$file
+done
+
