#4137 applying patch to enable new information system , obsolites #4045, #3992, #4081

diff --git a/skel/share/dCacheConfigure/modules/config_sedcache b/skel/share/dCacheConfigure/modules/config_sedcache
--- a/skel/share/dCacheConfigure/modules/config_sedcache
+++ b/skel/share/dCacheConfigure/modules/config_sedcache
@@ -1014,11 +1014,15 @@ yaim_state_java_path()
     local javaloc
     RET=""
     if [ -n "$JAVA_LOCATION" ] ; then
+      yaimlog INFO "Setting \$JAVA_LOCATION in site-info.def is depricated."
+      yaimlog INFO "The Java path is now configured through /etc/java/java.conf"
+      
       javaloc=${JAVA_LOCATION}/bin/java
       if [ -x "${javaloc}" ] ; then
         RET=$javaloc
       else
-        echo WARNING: Could not find Java at $javaloc
+        yaimlog ERROR "Could not find Java at $javaloc"
+        exit 1
       fi
     fi
     if [ -z "$RET" ] ; then
@@ -1197,20 +1201,17 @@ config_dcache_config_file_generate_node_config()
 }
 
 
-config_dcache_config_file_pool_path() 
+config_dcache_config_pools() 
 {
-  yaimlog DEBUG "function config_dcache_config_file_pool_path start"
-  local file2update
-  local DESTINATION
-  local SOURCE
-  SOURCE=$1
-  DESTINATION=$2
+  yaimlog DEBUG "function config_dcache_config_pools start"
+  #local file2update
   #yaim_config_file_update_prepare ${DESTINATION}
   #file2update=$RET
   #rm -f ${file2update}
   #touch ${file2update}
   yaim_query_conf_dcache_pool_node_size_path
   localpools=$RET
+  #echo YYYYYYYYYYYYYYYYYYYY $localpools
   let alreadyexistingpools=`/opt/d-cache/bin/dcache pool ls | wc -l`
   let alreadyexistingpools="$alreadyexistingpools-3"
   for poolspec in `echo $localpools`
@@ -1238,7 +1239,7 @@ config_dcache_config_file_pool_path()
         yaimlog WARNING "pool size must be larger than 4Gb"
       else
         poolExists=$( /opt/d-cache/bin/dcache pool ls | grep ${pool} )
-	    if [ -z "$poolExists" ] ; then
+        if [ -z "$poolExists" ] ; then
           /opt/d-cache/bin/dcache pool create ${size}G ${pool}
           poolcreaterc=$?
           if [ "$poolcreaterc" == "0" ] ; then
@@ -1246,7 +1247,7 @@ config_dcache_config_file_pool_path()
             while [ ${notnamed} == "0" ]
             do
               poolname=`hostname`_${alreadyexistingpools}
-              poolExists=$( /opt/d-cache/bin/dcache pool ls | grep ${hostname} )
+              poolExists=$( /opt/d-cache/bin/dcache pool ls | grep ${poolname} )
               if [ -z "$poolExists" ] ; then
                 /opt/d-cache/bin/dcache pool add ${poolname} ${pool}
                 namedPoolrc=$?
@@ -1254,18 +1255,20 @@ config_dcache_config_file_pool_path()
                   yaim_state_service_restart_needed pool
                   notnamed="1"
                 fi
+              else
+                yaimlog INFO "Pool name ${poolname} already exists creating new pool name."
               fi
               # Now we add 1 to the number of the next pool cell name
               let alreadyexistingpools="$alreadyexistingpools+1"
             done
           fi
         else
-	      yaimlog ERROR "${poolExists}"
-	    fi
+          yaimlog ERROR "${poolExists}"
+        fi
       fi
     fi
   done
-  yaimlog DEBUG "function config_dcache_config_file_pool_path stop"
+  yaimlog DEBUG "function config_dcache_config_pools stop"
 }
 
 
@@ -1319,9 +1322,6 @@ config_dcache_config_file()
         "etc/node_config")
             config_dcache_config_file_generate_node_config "${FILETOPROCESS}" "${DIRECTORY}/${DESTFILE}"
         ;;
-        #"etc/pool_path")
-        #    config_dcache_config_file_pool_path "${FILETOPROCESS}" "${DIRECTORY}/${DESTFILE}"
-        #;;
         "etc/dcache.kpwd")
             yaimlog DEBUG "Generated by cron so skipping '${FILETOPROCESS}'"
         ;;
@@ -2322,10 +2322,10 @@ config_sedcache_run()
   yaim_query_conf_node_dcache_name_server
   rcNameServer=$?
   if [ "${rcadmin}${rcclient}${rcdoor}${rcNameServer}${rcNameServer}" == "00000" ]; then
-    echo "[ERROR]: This host was not recognized as admin,pool or door"
-    echo "[ERROR]: Please check variables DCACHE_ADMIN and DCACHE_POOL"
-    echo "[ERROR]: or for door nodes the variables DCACHE_DOOR_SRM,"
-    echo "[ERROR]: DCACHE_DOOR_GSIFTP,DCACHE_DOOR_GSIDCAP,DCACHE_DOOR_DCAP"    
+    yaimlog ERROR "This host was not recognized as admin,pool or door"
+    yaimlog ERROR "Please check variables DCACHE_ADMIN and DCACHE_POOL"
+    yaimlog ERROR "or for door nodes the variables DCACHE_DOOR_SRM,"
+    yaimlog ERROR "DCACHE_DOOR_GSIFTP,DCACHE_DOOR_GSIDCAP,DCACHE_DOOR_DCAP"    
     exit 1
   fi
   requires DCACHE_ADMIN DCACHE_POOLS
@@ -2350,7 +2350,7 @@ config_sedcache_run()
     requires DCACHE_ADMIN DCACHE_POOLS
     config_dcache_config_files
     config_sedcache_check_sanity || exit $?
-    config_dcache_config_system_files
+    config_dcache_config_system_files    
   else
     echo "Skipping D-Cache config Reset"
   fi
@@ -2358,7 +2358,7 @@ config_sedcache_run()
   
   config_sechimera_run
   config_sepnfs_run
-  config_gip_dcache_run
+  config_gip_dcache_info_run
   config_dcache_config_dcache_scripts  
   config_dcache_pnfs_databases
   yaim_query_conf_voms
@@ -2374,7 +2374,7 @@ config_sedcache_run()
   if [ "${rcadmin}" == "1" ]; then
     yaim_config_pool_manager_add_lines
   fi
-  config_dcache_config_file_pool_path
+  config_dcache_config_pools
   yaim_state_service_restart_needed_do
   #Setup the Cron scripts
   config_sedcache_cron
