systemtest: add support for generating user credentials
Add support for the --user option.  This will use the disposable
CA to generate user credentials in addition to the host credentials.

The existing generated certificate's CN and subjectAltName (email) are
used as default CN and subjectAltName, if present, otherwise the git
'user.name' and 'user.email' config options are used.  Either may be
overwritten by specifying command-line options.

The script will store these credentials in ~/.globus.  If there is
no existing default credential then it will set the freshly created
credential as the default; but, otherwise, it will leave the existing
default credential alone.

If --generate is specified and existing user credentials are detected
then the --user option is assumed.

Target: master
Patch: http://rb.dcache.org/r/6954/
Acked-by: Gerd Behrmann

diff --git a/packages/system-test/src/main/bin/credentials b/packages/system-test/src/main/bin/credentials
--- a/packages/system-test/src/main/bin/credentials
+++ b/packages/system-test/src/main/bin/credentials
@@ -2,6 +2,8 @@
 
 set -e
 
+name=$(basename $0)
+
 rel_path=@TARGET@/dcache/etc/grid-security
 mkdir -p $rel_path/certificates
 TARGET_DIR=$(cd $rel_path;pwd)
@@ -24,6 +26,21 @@ while [ $# -gt 0 ]; do
 	    shift
 	    ;;
 
+	--user)
+	    user=1
+	    shift
+	    ;;
+
+	--name=*)
+	    username=${1##--name=}
+	    shift
+	    ;;
+
+	--email=*)
+	    email=${1##--email=}
+	    shift
+	    ;;
+
 	--clean)
 	    clean=1
 	    shift
@@ -36,20 +53,23 @@ while [ $# -gt 0 ]; do
 
 	--help|-h)
 	    echo "Usage:"
-	    echo "    $0 --generate [--only-localhost]"
-	    echo "    $0 --install"
-	    echo "    $0 --clean"
+	    echo "    $name --generate [--only-localhost] [--user [--name=<name>] [--email=<email>]]"
+	    echo "    $name --install"
+	    echo "    $name --clean"
 	    echo
-	    echo "Tool for managing grid host credentials suitable for testing dCache"
+	    echo "Tool for managing grid host and user X.509 credentials suitable for testing dCache"
 	    echo
 	    echo "Commands:"
-	    echo "     --generate        create new CA and host credentials"
-	    echo "     --install         install (\"trust\") any missing certificate material"
-	    echo "     --clean           remove managed files from the ~/.globus directory"
-	    echo "  -h --help            provide this information"
+	    echo "     --generate         create new CA and host credentials, and optionally user credentials"
+	    echo "     --install          install (\"trust\") any missing certificate material"
+	    echo "     --clean            remove managed files from the ~/.globus directory"
+	    echo "  -h --help             provide this information"
 	    echo
 	    echo "Options:"
-	    echo "     --only-localhost  only include 'localhost' as subjAltName"
+	    echo "     --only-localhost   only include 'localhost' as subjAltName in host certificate"
+	    echo "     --user             also generate a user certificate"
+	    echo "     --name=<name>      use <name> instead of output from 'git config user.name'"
+	    echo "     --email=<address>  use <address> instead of output from 'git config user.emil'"
 	    echo
 	    echo "This tool has three modes of operation: generating new credentials,"
 	    echo "trusting dCache credentials and removing files.  These correspond to"
@@ -59,9 +79,15 @@ while [ $# -gt 0 ]; do
 	    echo
 	    echo "The --generate command will create CA credentials (a private key and"
 	    echo "self-signed certificate) and, using this CA, generate host credentials"
-	    echo "(another private key and certificate).  Once the CA key has been used to"
-	    echo "sign the host certificate, it is destroyed.  Therefore, this CA cannot sign"
-	    echo "any further certificates."
+	    echo "(another private key and certificate).  It can optionally generate user"
+	    echo "credentals (another private key and certificate) that may be used to authenticate"
+	    echo "as a user when testing dCache."
+	    echo
+            echo "The CA's private key is destroyed after it has been used to sign the host"
+	    echo "certificate and any user certificate.  Therefore, this CA cannot sign any further"
+	    echo "certificates, which allows the CA to be trusted unequivocally.  Fresh"
+	    echo "credentials may be generated only by re-running this script, which will"
+	    echo "generate a fresh CA."
 	    echo
 	    echo "The generated CA certificate and host credentials are stored in the"
 	    echo "current system-test deployment and also in the users ~/.globus directory."
@@ -84,6 +110,27 @@ while [ $# -gt 0 ]; do
 	    echo "connects to 'localhost'.  It is generic, so may be stored in a VCS."
 	    echo "However, on some platforms, clients that use Globus native libraries"
 	    echo "seem unable to use this certificate."
+	    echo
+	    echo "User credentials"
+	    echo
+	    echo "The --user option requests that user credentials are generated in addition to"
+	    echo "host credentials.  The user credentials are stored in the ~/.globus directory as"
+	    echo "the files dcache-systemtest-usercert.pem and dcache-systemtest-userkey.pem."
+	    echo
+	    echo "Globus applications typically uses the usercert.pem and userkey.pem files in ~/.globus"
+	    echo "as the default credential.  If these default credential files do not exist or are under"
+	    echo "this script's control then they are updated so they point to the newly generated"
+	    echo "credential."
+	    echo
+	    echo "If user credentials have been generated in the past and host credentials are to be"
+	    echo "regenerated then the user credentials are automatically regenerated (i.e., the"
+	    echo "--user option is assumed)."
+	    echo
+	    echo "User credentials are generated with a name (e.g., 'Fred Bloggs') and an email"
+	    echo "address (e.g., 'fred.bloggs@example.org').  These may be supplied explicitly via the"
+	    echo "--name and --email options, respectively.  If either option is not specified then the"
+	    echo "corresponding value is taken from the existing generated certificate, if present, or"
+	    echo "the user's git configuration otherwise."
 	    echo
 	    echo "TRUST"
 	    echo
@@ -121,6 +168,51 @@ if [ "$only_localhost" = "1" ] && [ ! "$generate" = "1" ]; then
     exit 1
 fi
 
+if [ "$generate" = "1" ] &&
+    [ -f "$HOST_CRED_STORE/dcache-systemtest-usercert.pem" ] &&
+    [ -f "$HOST_CRED_STORE/dcache-systemtest-userkey.pem" ]; then
+    # Always regenerate usercert if we are generating host credential
+    # and there is an existing user credential.
+    user=1
+fi
+
+if [ "$user" = "1" ]; then
+    if [ ! "$generate" = "1" ]; then
+	echo "The --user flag only has effect if --generate is also specified. See --help"
+	echo "for details."
+	exit 1
+    fi
+
+    if [ "$username" = "" ] && [ -f $HOST_CRED_STORE/dcache-systemtest-usercert.pem ]; then
+	username=$(openssl x509 -in $HOST_CRED_STORE/dcache-systemtest-usercert.pem -noout -text -certopt no_extensions,no_sigdump,no_issuer,no_signame,no_serial,no_version,no_header,no_pubkey,no_validity|sed 's/.*CN=//')
+    fi
+
+    if [ "$username" = "" ]; then
+	username=$(git config user.name)
+    fi
+
+    if [ "$email" = "" ] && [ -f $HOST_CRED_STORE/dcache-systemtest-usercert.pem ]; then
+	email=$(openssl x509 -in $HOST_CRED_STORE/dcache-systemtest-usercert.pem -noout -noout -email|head -1)
+    fi
+
+    if [ "$email" = "" ]; then
+	email=$(git config user.email)
+    fi
+else
+    if [ ! "$username" = "" ]; then
+	echo "The --name option only has effect if --user is also specified. See --help"
+	echo "for details."
+	exit 1
+    fi
+
+    if [ ! "$email" = "" ]; then
+	echo "The --email option only has effect if --user is also specified. See --help"
+	echo "for details."
+	exit 1
+    fi
+fi
+
+
 if [ ! "$clean$install$generate" = "1" ]; then
     echo "Exactly one of --clean, --install and --generate must be specified.  Try --help for"
     echo "details."
@@ -130,6 +222,16 @@ fi
 clean_dot_globus()
 {
     rm -f $HOST_CRED_STORE/dcache-systemtest-host*.pem
+
+    if [ -h $HOST_CRED_STORE/usercert.pem ] &&
+	[ "$(readlink $HOST_CRED_STORE/usercert.pem)" = dcache-systemtest-usercert.pem ] &&
+	[ -h $HOST_CRED_STORE/userkey.pem ] &&
+	[ "$(readlink $HOST_CRED_STORE/userkey.pem)" = dcache-systemtest-userkey.pem ]; then
+	rm $HOST_CRED_STORE/usercert.pem
+	rm $HOST_CRED_STORE/userkey.pem
+    fi
+
+    rm -f $HOST_CRED_STORE/dcache-systemtest-user*.pem
 
     if [ -d $OUR_TRUST_STORE ]; then
 	for file in $OUR_TRUST_STORE/*; do
@@ -160,6 +262,14 @@ cleanup_ca_dir()
 }
 
 if [ "$generate" = "1" ]; then
+
+    if [ -f "$HOST_CRED_STORE/dcache-systemtest-usercert.pem" ] &&
+	[ -f "$HOST_CRED_STORE/dcache-systemtest-userkey.pem" ]; then
+	# Always regenerate usercert if we are generating host credential
+	# and there is an existing user credential.
+	user=1
+    fi
+
     CA_DIR=$(mktemp -d tmp.XXXXXXXXXX)
 
     trap cleanup_ca_dir EXIT
@@ -215,7 +325,6 @@ serial           = $CA_SERIAL
 crlnumber        = $CA_DIR/crlnumber
 crl              = $CA_DIR/crl.pem
 RANDFILE         = $CA_DIR/rand
-x509_extensions  = host_cert
 name_opt         = ca_default
 cert_opt         = ca_default
 default_days     = 365
@@ -231,7 +340,18 @@ keyUsage               = critical,digitalSignature,keyEncipherment,dataEncipherm
 nsComment              = "dCache.org disposable CA generated host certificate"
 subjectKeyIdentifier   = hash
 authorityKeyIdentifier = keyid,issuer
-subjectAltName         = @alt_names
+subjectAltName         = @host_alt_names
+extendedKeyUsage       = serverAuth,clientAuth
+issuerAltName          = issuer:copy
+certificatePolicies    = 2.5.29.32.0
+
+[user_cert]
+basicConstraints       = critical,CA:FALSE
+keyUsage               = critical,digitalSignature,keyEncipherment,dataEncipherment
+nsComment              = "dCache.org disposable CA generated user certificate"
+subjectKeyIdentifier   = hash
+authorityKeyIdentifier = keyid,issuer
+subjectAltName         = @user_alt_names
 extendedKeyUsage       = serverAuth,clientAuth
 issuerAltName          = issuer:copy
 certificatePolicies    = 2.5.29.32.0
@@ -241,21 +361,27 @@ certificatePolicies    = 2.5.29.32.0
 DC = match
 DC = match
 CN = supplied
-
-[alt_names]
 EOF
 
     i=1
+    echo "" >> $CA_CONFIG
+    echo "[host_alt_names]" >> $CA_CONFIG
     for fqdn in $(list_potential_subjaltname | sort | uniq); do
 	echo "DNS.$i = $fqdn" >> $CA_CONFIG
 	i=$(( $i + 1 ))
     done
 
+    if [ "$user" = "1" ]; then
+	echo "" >> $CA_CONFIG
+	echo "[user_alt_names]" >> $CA_CONFIG
+	echo "email = $email" >> $CA_CONFIG
+    fi
+
     touch $CA_INDEX
     echo 01 > $CA_SERIAL
     openssl req -batch -new -x509 -config $CA_CONFIG -days 365 -keyout $CA_DIR/ca-key.pem -out $CA_DIR/ca-cert.pem >/dev/null 2>&1
     CN=host/localhost openssl req -new -config $CA_CONFIG -keyout $CA_DIR/hostkey.pem -out $CA_DIR/hostcert.req  >/dev/null 2>&1
-    openssl ca -batch -config $CA_CONFIG -out $CA_DIR/hostcert.pem  -infiles $CA_DIR/hostcert.req >/dev/null 2>&1
+    openssl ca -batch -config $CA_CONFIG -extensions host_cert -out $CA_DIR/hostcert.pem  -infiles $CA_DIR/hostcert.req >/dev/null 2>&1
 
     hash_old=$(openssl x509 -in $CA_CERT -noout -subject_hash_old)
     hash_new=$(openssl x509 -in $CA_CERT -noout -subject_hash)
@@ -279,6 +405,41 @@ EOF
 
     cp $TARGET_DIR/hostcert.pem $HOST_CRED_STORE/dcache-systemtest-hostcert.pem
     cp $TARGET_DIR/hostkey.pem $HOST_CRED_STORE/dcache-systemtest-hostkey.pem
+
+
+    if [ "$user" = "1" ]; then
+	CN=$username openssl req -new -config $CA_CONFIG -keyout $CA_DIR/userkey.pem -out $CA_DIR/usercert.req  >/dev/null 2>&1
+	openssl ca -batch -config $CA_CONFIG -extensions user_cert -out $CA_DIR/usercert.pem  -infiles $CA_DIR/usercert.req >/dev/null 2>&1
+
+	mv $CA_DIR/usercert.pem $HOST_CRED_STORE/dcache-systemtest-usercert.pem
+	mv $CA_DIR/userkey.pem $HOST_CRED_STORE/dcache-systemtest-userkey.pem
+
+	chmod 400 $HOST_CRED_STORE/dcache-systemtest-userkey.pem
+
+	if [ ! -e $HOST_CRED_STORE/usercert.pem ] && [ ! -e $HOST_CRED_STORE/userkey.pem ]; then
+	    ln -s dcache-systemtest-usercert.pem $HOST_CRED_STORE/usercert.pem
+	    ln -s dcache-systemtest-userkey.pem $HOST_CRED_STORE/userkey.pem
+	else
+	    echo "User credential installed as:"
+	    echo
+	    echo "    $HOST_CRED_STORE/dcache-systemtest-usercert.pem"
+	    echo "    $HOST_CRED_STORE/dcache-systemtest-userkey.pem"
+	    echo
+	    echo "The default credentials:"
+	    echo
+	    echo "    $HOST_CRED_STORE/usercert.pem"
+	    echo "    $HOST_CRED_STORE/userkey.pem"
+	    echo
+            echo "already exist and point to some other credential.  Because of this, they have not been touched."
+	    echo
+	    echo "If you want to use the freshly install credentials as your default credentials then first move"
+	    echo "the existing usercert.pem and userkey.pem files out of the way and then do:"
+	    echo
+	    echo "    ln -s dcache-systemtest-usercert.pem $HOST_CRED_STORE/usercert.pem"
+	    echo "    ln -s dcache-systemtest-userkey.pem $HOST_CRED_STORE/userkey.pem"
+	    echo
+	fi
+    fi
 fi
 
 
