get rid of annoying SRM_PATH warning http://rb.dcache.org/r/843/

diff --git a/modules/srmclient/bin/srm-storage-element-info b/modules/srmclient/bin/srm-storage-element-info
--- a/modules/srmclient/bin/srm-storage-element-info
+++ b/modules/srmclient/bin/srm-storage-element-info
@@ -1,19 +1,25 @@
 #!/bin/sh
-if [ "$SRM_PATH" = "" ]
-then
-   command=`which $0`
-   commanddir=`dirname $command`
-   SRM_PATH=`dirname $commanddir`
-   if [ -x $SRM_PATH/sbin/srm ]
-   then
-      export SRM_PATH
-   else
-      echo "cannot determine path to srm product, please define and export SRM_PATH enviroment variable" 1>&1
-      exit 1
-   fi
-else
-  echo "WARNING: SRM_PATH is defined, which might cause a wrong version of srm client to be executed" 2>&1
-  echo "WARNING: SRM_PATH=$SRM_PATH" 2>&1
+
+command=`which $0`
+commanddir=`dirname $command`
+OUR_PATH=`dirname $commanddir`
+
+if [ "$SRM_PATH" != "" -a "$SRM_PATH" != "${OUR_PATH}" ]
+    then
+    echo "WARNING: SRM_PATH is defined, but does not point to the expected place " 2>&1
+    echo "WARNING: a wrong version of srm client may be executed " 2>&1
+    echo "WARNING: SRM_PATH=$SRM_PATH " 2>&1
+    echo "WARNING: expected path ${OUR_PATH} " 2>&1
+elif [ "$SRM_PATH" = "" ]
+    then
+    SRM_PATH=${OUR_PATH}
+    export SRM_PATH
+fi
+
+if [ ! -x $SRM_PATH/sbin/srm ]
+    then
+    echo "cannot determine path to srm product, please define and export SRM_PATH enviroment variable" 1>&1
+    exit 1
 fi
 
 $SRM_PATH/sbin/srm -getStorageElementInfo $*
