prevent srm from starting twice, reliably kill the srm on shutdown

diff --git a/skel/bin/dcache-srm b/skel/bin/dcache-srm
--- a/skel/bin/dcache-srm
+++ b/skel/bin/dcache-srm
@@ -18,15 +18,56 @@ hostname=`hostname | awk -F. '{print $1}'`
 export JAVA_HOME
 export JAVA_OPTS
 export CATALINA_HOME=${TOMCAT_BASE_PATH}/apache-tomcat-5.5.20
-export CATALINA_PID=${ourHomeDir}/config/lastPid.srm-${hostname}
+export config=${ourHomeDir}/config
+export CATALINA_PID=${config}/lastPid.srm-${hostname}
 
 export X509_CERT
 export X509_KEY
 export SRM_V2_PORT
 
+procStop() {
+   if [ ! -f ${CATALINA_PID} ] ; then
+      echo "Cannot find appropriate pid file (${CATALINA_PID})" 1>&2
+      exit 0
+   fi
+   x=`cat ${CATALINA_PID}`
+   if [ -z "$x" ] ; then
+      echo "Pid file (${CATALINA_PID}) does not contain valid PID" 1>&2
+      exit 1
+   fi
+   touch ${config}/realStop.lastPid.srm-${hostname} 2>/dev/null
+   kill -TERM $x 1>/dev/null 2>/dev/null
+   printf "Stopping srm-${hostname} (pid=`cat ${CATALINA_PID}`) "
+
+   for c in  0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
+     kill -0 $x 1>/dev/null 2>/dev/null
+     if [ $? -ne 0 ] ; then
+        rm -f $CATALINA_PID
+        echo "Done"
+        exit 0
+     fi
+     printf "$c "
+     sleep 1
+     if [ $c -eq 9 ] ; then
+         kill -9 $x
+     fi
+   done
+   echo "Giving up : srm-${hostname} might still be running" 1>&2
+   exit 4
+
+}
 
 case $cmd1 in
   start)
+        if [ -f ${CATALINA_PID} ] ; then
+          x=`cat ${CATALINA_PID}`
+          kill -0 $x 1>/dev/null 2>/dev/null
+          if [ $? -eq 0 ] ; then
+            echo "srm-${hostname} might still be running" 1>&2
+            exit 4
+          fi
+        fi
+
         ${TOMCAT_BASE_PATH}/apache-tomcat-5.5.20/bin/startup.sh
         RETVAL=$?
         echo
@@ -40,6 +81,7 @@ case $cmd1 in
         ;;
   stop)
          ${TOMCAT_BASE_PATH}/apache-tomcat-5.5.20/bin/shutdown.sh
+          procStop
           RETVAL=$?
           echo
           [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/srm-tomcat
