debian: Systemd integration
Motivation:

The world is moving to systemd.

Modification:

This patch integrates dCache with systemd. The approach taken is to fully
integrate with the features offered by systemd rather than trying to wrap
xisting code that duplicates functionality alread offered by systemd. This
means:

- No daemon script - systemd invokes the java process directly.

- Systemd monitors the java process and restarts it if it quits
  unexpectedly.

- There are no PID files.

- There is no restart file.

- Systemd captures the stdout/stderr output of the process and
  directs it to journald.

- No dcache.local.sh or dcache.local.run.sh files are sourced -
  use the customization features of systemd to adjust resource
  limits or invoke scripts during startup.

- Systemd drops privileges of the java process.

- Systemd restricts access to file system areas dCache should not
  have access to.

To enable the above, the dcache-generator script is installed as a systemd
generator. This script generates systemd units corresponding to the current
configuration - one unit per domain. This means that whenever the configuration
changes, systemd has to be reloaded by invoking `systemctl daemon-reload`. This
is done automatically whenever dcache is upgraded and whenever the `dcache`
script is invoked as root. Otherwise the admin needs to invoke the reload
command by hand.

Our scripts have been updated to invoke systemctl instead of running our daemon
script - this is achieved by renaming services.sh to services-daemon.sh and
adding a services-systemd.sh; the postinstall script detects the pressence of
systemd and symlinks the proper script to services.sh. services-systemd.sh
provides compatible shell functions for all functions in services-daemon.sh
called from the outside.

Since systemd control startup and shutdown of the java process, we no longer
control the transition from SIGTERM to SIGKILL and thus cannot indicate this
in our shutdown animation.

stdout is redirected to journald by default. This can be customized through
systemd. Since journald already includes a timestamp with each message, the
timestamp in our default log format becomes redundant. The postinst script thus
changes the default log format to not include a timestamp when it detects
systemd. Since we change the log format anyway, I chose to also include the log
level of the message and move the diagnostic context to the end of the message
(to make reading the messages easier).

An admin can customize logback.xml if one wants a classic log file; or can
adjust the unit configuration to log through syslog.

Upon upgrading, existing SysV init links are removed as is the init script.

The generated systemd units are not enabled by default - ie they will not be
started at boot. One has to enable these using the `systemctl enable` command.
Since a unit per domain is generated, one has to enable startup per domain.

Result:

Systemd enabled Debian packages - see above for details.

Target: trunk
Require-notes: yes
Require-book: yes
Acked-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>

Reviewed at https://rb.dcache.org/r/10079/

diff --git a/skel/bin/dcache b/skel/bin/dcache
--- a/skel/bin/dcache
+++ b/skel/bin/dcache
@@ -294,6 +294,27 @@ poolDumpYaml() # $1 = domain, $2 = cell
     CLASSPATH="$classpath" quickJava org.dcache.pool.repository.MetaDataYamlTool "$path" "$type"
 }
 
+# Prints all domains that match a given pattern. Prints all domains if
+# no patterns are provided. Fails if a pattern matches no domains.
+printDomains() # $1+ = patterns
+{
+    local domain
+    local domains
+    domains=$(getProperty dcache.domains)
+    if [ $# -eq 0 ]; then
+        echo $domains
+    else
+        for pattern in "$@"; do
+            hasMatch "$pattern" $domains || fail 1 "$pattern: No such domain"
+        done
+        for domain in $domains; do
+            if matchesAny "$domain" "$@"; then
+                echo $domain
+            fi
+        done
+    fi
+}
+
 if [ $# -eq 0 ]; then
     usage
 fi
